### ISSUE TITLE
Get application file size

### ISSUE THREAD

**Issue by rafaelje** [glpi-project/android-inventory-library#104]
The file size of the app alwais is "0" or empty, I'm trying to find a way to get this file size but all that I found are a tricky way

https://stackoverflow.com/questions/28791461/ipackagestatsobserver-cannot-be-resolved-to-a-type-android

https://www-jo.se/f.pfleger/android-package-size

These method to get the file size are asynchronous and is need to convert into synchronous

**Comment by Ivans51** [comment]
@rafaelje this issue was solved in PR previous https://git.io/fA7cX
```XML
<SOFTWARES>
	<NAME><![CDATA[Hellofood]]></NAME>
	<COMMENTS>com.global.hellofood.android</COMMENTS>
	<VERSION>2.6.5</VERSION>
	<FILESIZE>4470311</FILESIZE>
	<FROM>Android</FROM>
	<INSTALLDATE>1443434641000</INSTALLDATE>
	<FOLDER>/system/vendor/operator/app/pre.hf.moviestar.mx-release</FOLDER>
	<NO_REMOVE>1</NO_REMOVE>
	<USERID>10112</USERID>
</SOFTWARES>
```
