### ISSUE TITLE
DevOps tasks

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#109]
- [ ] Continuous integration
- [ ] Continuous deployment
- [ ] Changelog
- [ ] Test reports
- [ ] Coverage reports
- [ ] Code documentation
- [ ] Artifacts for downloads and release description

**Comment by ajsb85** [comment]
## List of tools

### Transifex

Languages

https://www.transifex.com/

### Fastlane

Deploy to Google Play and take screenshoots

https://fastlane.tools/

### Standard-version

Automatic versioning and CHANGELOG generation, using GitHub's squash button and conventional commit messages.

https://github.com/conventional-changelog/standard-version

### conventional-github-releaser

Create a github release

https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-github-releaser

### Gradle

Build Android

https://gradle.org/

### Javadoc

Create java documentation

### Bintray

Publish libraries

## Workflow for Android Java Library

### on any branch
- build

### on develop
- Pull transifex languages without commit (not implemented)
- Build
- Test
- Update java documentation on gh-page
- Generate and update CHANGELOG on gh-page
- Generate and update COVERGE REPORT on gh-page
- Deploy on Bintray like a beta (not implemented)
- When you make a commit in the branch the circle start again find a way to stop if not requiere

### on master
- Pull transifex languages (not implemented)
- Build
- Test
- Generate and update version and commit
- Update java documentation on gh-page
- Generate and update CHANGELOG on gh-page
- Generate and update COVERGE REPORT on gh-page
- Create a new tag
- Create a github release
- Deploy on Bintray
- When you make a commit in the branch the circle start again find a way to stop if not requiere

**Comment by Naylin15** [comment]
Hi, @ajsb85 @rafaelje 

The workflow is very much the same, except for these 3 aspects:

The changelog is generated only on Master branch
The documentation is generated only on develop branch
Tests are being run only in develop and feature branches

This is according to the information at the moment of documenting the workflow on the project sites

[Workflow article - Continuous Integration](http://flyve.org/android-inventory-library/howtos/workflow#continuous-integration)

Also, checking past issues, I think we can close this one, #38 , the features requested are currently working

Thank you

**Comment by rafaelje** [comment]
@Naylin15 I'll close this issue you are right https://github.com/flyve-mdm/android-inventory-library/issues/38

**Comment by ajsb85** [comment]
I agree, but this task is waiting for review step by step with @rafaelje and me.
