### ISSUE TITLE
Use of CDATA for software names 

### ISSUE THREAD

**Issue by DIOHz0r** [glpi-project/android-inventory-library#113]
**Describe the bug**
The XML generate doesn't handle the names with spacial chars like "&" which gives a XML malformed.

**To Reproduce**
1. Install an app like Kingdoms & Lords (com.gameloft.android.GloftKLMF)
2. Generate an inventory
3. Check the software name

**Expected behavior**
The software names must use the CDATA node to escape the special chars

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1426313/39604618-f2ce9caa-4efa-11e8-9e5b-8317b6ac4f85.png)

**Comment by ajsb85** [comment]
Let's discuss about it with @btry and @g-bougard

**Comment by btry** [comment]
Let's try to import such XML and see how Fusion behaves

**Comment by g-bougard** [comment]
From [FusionInventory Inventory protocol](http://fusioninventory.org/documentation/dev/spec/protocol/inventory.html), `<SOFTWARES/>` nodes can report:
```
    <!ELEMENT SOFTWARES (COMMENTS, FILESIZE, FOLDER, FROM, HELPLINK,
     INSTALLDATE, NAME, NO_REMOVE, RELEASE_TYPE, PUBLISHER,
     UNINSTALL_STRING, URL_INFO_ABOUT, VERSION, VERSION_MINOR,
     VERSION_MAJOR, GUID, ARCH, USERNAME, USERID, SYSTEM_CATEGORY)>
       <!ELEMENT COMMENTS (#PCDATA)>
       <!ELEMENT FILESIZE (#PCDATA)>
       <!ELEMENT FOLDER (#PCDATA)>
       <!-- information source, ie 'registry', 'rpm', 'deb', etc. ->
       <!ELEMENT FROM (#PCDATA)>
       <!ELEMENT HELPLINK (#PCDATA)>
       <!-- installation date, in DD/MM/YYYY format -->
       <!ELEMENT INSTALLDATE (#PCDATA)>
       <!ELEMENT NAME (#PCDATA)>
       <!-- wether the software can be uninstalled (0|1) -->
       <!ELEMENT NO_REMOVE (#PCDATA)>
       <!ELEMENT RELEASE_TYPE (#PCDATA)>
       <!ELEMENT PUBLISHER (#PCDATA)>
       <!ELEMENT UNINSTALL_STRING (#PCDATA)>
       <!ELEMENT URL_INFO_ABOUT (#PCDATA)>
       <!ELEMENT VERSION (#PCDATA)>
       <!ELEMENT VERSION_MINOR (#PCDATA)>
       <!ELEMENT VERSION_MAJOR (#PCDATA)>
       <!-- software GUID (Windows only) -->
       <!ELEMENT GUID (#PCDATA)>
       <!-- software architecture -->
       <!ELEMENT ARCH (#PCDATA)>
       <!-- software owner name -->
       <!ELEMENT USERNAME (#PCDATA)>
       <!-- software owner ID -->
       <!ELEMENT USERID (#PCDATA)>
       <!-- software system category  -->
       <!ELEMENT SYSTEM_CATEGORY (#PCDATA)>
```
Most are really optional and checking the sample screenshot, you need to format `<INSTALLDATE/>` to `DD/MM/YYYY` and you also should set the `<SYSTEM_CATEGORY/>` and `<PUBLISHER/>` if availables.
