### ISSUE TITLE
Handling foreign chars

### ISSUE THREAD

**Issue by DIOHz0r** [glpi-project/android-inventory-library#120]
**Describe the bug**
We found some problem handling special chars for French language for apps name. The XML is broken with binary data . 

I'm attaching two XML files, one with the problem and the other one has the XML well formet

**Additional context**
[inventory.zip](https://github.com/flyve-mdm/android-inventory-agent/files/2085067/inventory.zip)

**Comment by rafaelje** [comment]
I think the problem was in the library but was solved on the agent
