### ISSUE TITLE
No Simcards data reported

### ISSUE THREAD

**Issue by lalogrosz** [glpi-project/android-inventory-library#131]
I didn't recive the Simcards data in the mContent, and it is because the getState method returns a SIM_STATE_READY (and it is ok) but the condition is if the state is equal to "SIM_STATE_UNKNOWN"

There is a PR with the if condition added:
https://github.com/flyve-mdm/android-inventory-library/pull/72/files

I don't know why the state should be UNKNOWN instead of READY

**Comment by lalogrosz** [comment]
@ajsb85 I can do the PR if the solution is to change to READY

**Comment by rafaelje** [comment]
Thanks @lalogrosz fell free to create the PR if you need any help please let me know
