### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [glpi-project/android-inventory-library#14]
Hi, @rafaelje 

I will create gh-pages as requested in this issue: https://github.com/flyve-mdm/flyve-mdm.github.io/issues/13

Regards

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Please, re-create the gh-pages branch as orphan and empty.

Following these steps:
https://help.github.com/articles/creating-project-pages-using-the-command-line/

And please, add your issues and PRs with the Project ID 2 (Website) of this repository.

Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje.
The project site here at the moment:
http://flyve.org/flyve-mdm-android-inventory-agent/
I will close this issue.
Good job @Gianfranco97
