### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#147]
Hi, @Naylin15 
There are a lot of license headers outdated in the source code.

**Comment by Naylin15** [comment]
Hi,

Here is a draft [Hackmd](https://hackmd.io/0BOxyKUwRyKmhPA-EfrAMQ?view)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Add the email of the author or contributor.
And take care, some cases the files are created from scratch and not from FI.
OK for the draft. Thank you.
