### ISSUE TITLE
Feedback SD card volume usage

### ISSUE THREAD

**Issue by btry** [glpi-project/android-inventory-library#153]
Hi

In the latest mdm agent I noticed that my SD Card id not reported as a volume.

![image](https://user-images.githubusercontent.com/14139801/45700110-02a48a80-bb6c-11e8-8fff-95eae48e0672.png)

My 32GB sd card is missing

**Comment by Ivans51** [comment]
The problem is that SD card is type removable storage.
https://stackoverflow.com/a/31968333
the problem will be solved
