### ISSUE TITLE
IMEI information 

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#188]
Hi, @Ivans51 

Could you confirm if we already support this information and what we can do to get it.

Thank you.

**Comment by Ivans51** [comment]
Get information about categories?

**Comment by ajsb85** [comment]
Hi, @Ivans51 
Get information about IMEI.

**Comment by Ivans51** [comment]
I can get IMEI in this way
https://stackoverflow.com/a/14661104

**Comment by Ivans51** [comment]
What is the tag to add the IMEI at the inventory?

**Comment by ajsb85** [comment]
Hi, @g-bougard & @btry 
Any suggest for the category of the IMEI?

**Comment by btry** [comment]
Hi

mobile devices are saved in glpi as computers, and there is no field to save the IMEI. The best would be to implement a new component in GLPI of type "modem".

Once done we can spec the IMEI in the inventory for Fusion, implement it and finally implement it in the inventory library.

**Comment by ajsb85** [comment]
I agree with you Thierry.

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Help us with the documentation in the specifications for the FuisionInventory.
Submit a PR into the documentation of the FuisionInventory.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

Where should I add the tag IMEI? 

At the [Modems element](https://github.com/fusioninventory/fusioninventory.github.io/blob/master/documentation/dev/spec/protocol/inventory.md) or where it's shown in the PR #193 ?

Thank you

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Thierry suggest to add the IMEI in the MODEM; BTW, the device can support multiples IMEIs.

**Comment by Naylin15** [comment]
All right, merci !
