### ISSUE TITLE
Inventory modems in devices

### ISSUE THREAD

**Issue by btry** [glpi-project/android-inventory-library#198]
We need to inventory IMEI of mobile devices. 

While we impelment a new modem component in GLPI, we need to investigate how we can detect one or several modem devices in mobile assets.

A modem can have one or several sim cards, and some devices exists with several modems, handling each at least one simcard. Some devices can hold 4 simcards. https://en.wikipedia.org/wiki/Dual_SIM

  
#### Observed Results:

not implemented
  
#### Expected behavior:

detect modems and IMEI and feed the inventory XML or JSON. 

Note: we need first to spec the implemetnation of modems in GLPI before defining the spec of the inventory data (XML or JSON).

We may already expect something like (assuming there are 2 modems having each 2 IMEI numbers)
```xml
<MODEMS>
  <IMEI>12345678890124</IMEI>
  <IMEI>123467880912314</IMEI>
</MODEMS>
<MODEMS>
  <IMEI>12345678890124</IMEI>
  <IMEI>123467880912314</IMEI>
</MODEMS>
```

**Comment by Ivans51** [comment]
With this I can information about IMEI to differents slots
https://stackoverflow.com/a/47343983

And with this I can know the number of slot SIM cards that have the device
https://stackoverflow.com/a/36738983
