### ISSUE TITLE
Write a welcome article

### ISSUE THREAD

**Issue by Gianfranco97** [glpi-project/android-inventory-library#21]
Write a welcome article for the page, this first article should give a brief introduction to the product and serve as an entry point for for new users. The idea is to be able to use this for promotion.

Said article should be written in Markdown and be published in the branch of gh-pages within the folder "_post"

Steps to follow for publication:
1. Enter http://prose.io/
2. Select the Flyve MDM organization
3. Enter in repository where you want to publish the article
4. Change to the branch gh-pages
5. Click on the "NEW FILE" button
6. Write your article
7. Save your work

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Could you move from HackMD the press release draft to the news section of the project site using prose.io and reference this task?

And check the post as draft (no published yet)

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done [bad0d1c](https://github.com/flyve-mdm/flyve-mdm-android-inventory/commit/bad0d1c3f15bd96f9b3ab6ae2c0ef39be795129d)
