### ISSUE TITLE
TelephonyManager getDeviceId throws SecurityException

### ISSUE THREAD

**Issue by lalogrosz** [glpi-project/android-inventory-library#214]
If you have Android 8, getDeviceId is deprecated, also it needs READ_PHONE_STATE to be requested to the user, like the camera. The problem is in the catch in getJSON method, because ex.getCause() returns null and onTaskError callback is never fired. I had to debug to watch the SecurityException

**Smartphone (please complete the following information):**
 - Device: Samsung A8 
 - OS: Android 8

**Comment by stonebuzz** [comment]
Hi lalogrosz, can you test the latest version of develop branch.

Best regards

**Comment by stonebuzz** [comment]
Fixed
