### ISSUE TITLE
Removes root permission in Hardware

### ISSUE THREAD

**Issue by lalogrosz** [glpi-project/android-inventory-library#218]
I was chatting with Thierry in Telegram about the "su" execution in Hardware file.
He figured about it and told me that should be replace the implementation.
This is the commit https://github.com/flyve-mdm/android-inventory-library/commit/024b1547c657035824aa3374ade9878ecc1c2aa6

It's really necessary because I've clients rejecting the app for this permission.

![Screenshot_2019-06-11_09-46-50](https://user-images.githubusercontent.com/1898486/59273142-e41c7d00-8c2d-11e9-96a2-7d3513159e09.png)

**Comment by stonebuzz** [comment]
Hi @lalogrosz 

It's really necessary if client want more information on inventory.

They may refuse this permission definitively if they want.

From our point of view we offer both possibilities.

Best regards
