### ISSUE TITLE
Add titles on json to create a better titles

### ISSUE THREAD

**Issue by rafaelje** [glpi-project/android-inventory-library#46]
We can implement some improvements of the json with this format:

```
{
    "dateLastLoggedUser": {
     "title": "Date last logged user",
     "value": "08\/28\/17"
 }
```

**Comment by ajsb85** [comment]
@Rafaelje For the names of the field of the Inventory, we need to use a key (JSON or XML) and create a list of the strings for Transifex

**Comment by ajsb85** [comment]
So, this issue is invalid.
The idea is to support L10N
