### ISSUE TITLE
Enhance specs for batteries

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#56]
Hi, @rafaelje 

This is a report from @g-bougard

Android - Inventory Agent by @flyve-mdm 0.1.0:

```XML
<BATTERIES>
  <CHEMISTRY>Li-ion</CHEMISTRY>
  <TEMPERATURE>0.0c</TEMPERATURE>
  <VOLTAGE>4.278V</VOLTAGE>
  <LEVEL>99%</LEVEL>
  <HEALTH>Unknown</HEALTH>
  <STATUS>Dis-charging</STATUS>
</BATTERIES>
```

Linux FusionInventory 2.4.x (would be after related PR merged):

```XML
<BATTERIES>
  <NAME>SR Real Battery</NAME>
  <CAPACITY>28.0763 Wh</CAPACITY>
  <VOLTAGE>4.109V</VOLTAGE>
  <CHEMISTRY>lithium-ion</CHEMISTRY>
  <SERIAL>123456789</SERIAL>
  <MANUFACTURER>Intel SR 1</MANUFACTURER>
</BATTERIES>
```

Specs seems not followed by Android agent only CHEMISTRY & VOLTAGE seems common.

**Comment by rafaelje** [comment]
This is the official documentation of battery information API on Android:
https://developer.android.com/reference/android/os/BatteryManager.html

**Comment by Ivans51** [comment]
Hi @rafaelje. 
This issue was resolved, PR https://github.com/flyve-mdm/android-inventory-library/pull/157
