### ISSUE TITLE
Enhance specs for the BIOS

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#57]
Hi, @rafaelje 

This is a report from @g-bougard

Android - Inventory Agent by @flyve-mdm 0.1.0:

```XML
<BIOS>
  <BDATE>06/07/17</BDATE>
  <BMANUFACTURER>ASUSTeK COMPUTER INC.</BMANUFACTURER>
  <MMANUFACTURER>ASUSTeK COMPUTER INC.</MMANUFACTURER>
  <SMODEL>T102HA</SMODEL>
  <SSN>Unknown</SSN>
</BIOS>
```

Linux FusionInventory 2.4.x:

```XML
<BIOS>
  <ASSETTAG>No Asset Tag</ASSETTAG>
  <BDATE>04/12/2017</BDATE>
  <BMANUFACTURER>American Megatrends Inc.</BMANUFACTURER>
  <BVERSION>T102HA.303</BVERSION>
  <MMANUFACTURER>ASUSTeK COMPUTER INC.</MMANUFACTURER>
  <MMODEL>T102HA</MMODEL>
  <MSN>BSN12345678901234567</MSN>
  <SKUNUMBER>ASUS-TabletSKU</SKUNUMBER>
  <SMANUFACTURER>ASUSTeK COMPUTER INC.</SMANUFACTURER>
  <SMODEL>T102HA</SMODEL>
  <SSN>GBN0CX13R310459</SSN>
</BIOS>
```

This is specific to x86 platform as a BIOS is present, but I can see
few point are not matching for Android:

`<BDATE/>` seems wrong, taken from dmidecode on linux
`<BMANUFACTURER/>` is wrong as platform manufacturer is reported.
`<SSN/>` is missing and it is important as this is the device serial number.

**Comment by rafaelje** [comment]
This is the official Android documentation API to get information about the bios:
https://developer.android.com/reference/android/os/Build.html

**Comment by Ivans51** [comment]
In Android no exist information about the BIOS but handle something called BootLoader so can get information about the issue
https://stackoverflow.com/questions/12635820/what-is-bios-in-android

**Comment by Ivans51** [comment]
With cd /sys/class/dmi/id/ i can get information about BIOS and other components
```
bios_date
bios_vendor
bios_version
board_asset_tag
board_name
board_serial
board_vendor
board_version
chassis_asset_tag
chassis_serial
chassis_type
chassis_vendor
chassis_version
modalias
power
product_name
product_serial
product_uuid
product_version
smbios_version
subsystem
sys_vendor
uevent
```
