### ISSUE TITLE
Enhance Specs for Memories

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#63]
Hi, @rafaelje 

This is a report from @g-bougard

Android seems to report the available memory, not the installed physical memory.
Then it appears wrongly in "Components" tab in GLPI as CAPACITY is wrong
and TYPE is missing. SPEED is also missing.

Android - Inventory Agent by @flyve-mdm 0.1.0:

```XML
<MEMORIES>
  <DESCRIPTION>Memory</DESCRIPTION>
  <CAPACITY>3785</CAPACITY>
</MEMORIES>
```

Linux FusionInventory 2.4.x:

```XML
<MEMORIES>
  <CAPACITY>4096</CAPACITY>
  <CAPTION>A1_DIMM0</CAPTION>
  <DESCRIPTION>DIMM</DESCRIPTION>
  <MEMORYCORRECTION>Multi-bit ECC</MEMORYCORRECTION>
  <NUMSLOTS>1</NUMSLOTS>
  <SERIALNUMBER>A1_SerNum0</SERIALNUMBER>
  <SPEED>1600</SPEED>
  <TYPE>DDR3</TYPE>
</MEMORIES>
<MEMORIES>
  <CAPTION>A1_DIMM1</CAPTION>
  <DESCRIPTION>DIMM</DESCRIPTION>
  <MEMORYCORRECTION>Multi-bit ECC</MEMORYCORRECTION>
  <NUMSLOTS>2</NUMSLOTS>
  <SERIALNUMBER>A1_SerNum1</SERIALNUMBER>
</MEMORIES>
```

**Comment by rafaelje** [comment]
I cannot find information about how to get the speed or type for now programmatically with API or command shell

**Comment by g-bougard** [comment]
Hi, the real goal here is to report all hardware memory components, not the logically available or total detected memory.

**Comment by rafaelje** [comment]
@g-bougard I got the main idea, and that is the information that I cannot find yet

**Comment by Ivans51** [comment]
With /sys/bus/platform/drivers/ddr_type/ddr_type can get information about type memory in device root
```
LPDDR3_1600
```

**Comment by Ivans51** [comment]
In Android no exist slot to Memories
https://www.quora.com/Is-it-possible-to-increase-phone-RAM-from-1-GB-to-2-GB/answer/Deepak-Thakur-244

**Comment by Ivans51** [comment]
In Android the Ram is integrated, no is possible get information about caption
https://www.quora.com/Is-it-possible-to-add-physical-RAM-for-my-Android-phone/answer/Yves-Han

**Comment by Ivans51** [comment]
@rafaelje the information is complete in PR https://github.com/flyve-mdm/android-inventory-library/pull/141
