### ISSUE TITLE
Enhance Specs for Users

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#68]
Hi, @rafaelje 

This is a report from @g-bougard

Android - Inventory Agent by @flyve-mdm 0.1.0:

> Actual logged user is missing and should be the currently used account.

Linux @FusionInventory 2.4.x:

```XML
<USERS>
  <LOGIN>guillaume</LOGIN>
</USERS>
```

**Comment by rafaelje** [comment]
This is the possible value to do it

```
Build.USER
```

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I prefer this way:

https://developer.android.com/reference/android/os/UserManager.html#getUserName()

> Build.USER = The username in the machine of the developer that build the OS.

**Comment by rafaelje** [comment]
Both ways are implemented, getUserName() is available from API 17 and require MANAGE_USERS permission to work is any of this condition are not present will use Build.USER
