### ISSUE TITLE
Various Spec issues

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#69]
Hi, @rafaelje 

This is a report from @g-bougard

Android - Inventory Agent by @flyve-mdm 0.1.0:

 - `<FIREWALL/>` is missing but does it makes sens to have it on Android?
 - Found `<SIMCARDS/>` set to:
```XML
<SIMCARDS>
   <STATE>SIM_STATE_UNKNOWN</STATE>
</SIMCARDS>
```
   But as no SIM is present nor SIM slot, this node should not appear
 - `<CONTROLLERS/>` is missing but does it makes sens to have it on Android?
 - `<LOCAL_GROUPS/>` && `<LOCAL_USERS/>` are missing but does it makes sens to have it on Android?
   As you can share a device between several account, I think this may
   appear here as `<LOCAL_USERS/>`
 - `<VERSIONCLIENT/>` is empty
 - Android reports `<SOFTWARE/>` list in place of `<SOFTWARES/>` one. This is still reported in an issue.

**Comment by rafaelje** [comment]
Hi @ajsb85!

with `<FIREWALL/><CONTROLLERS/>` and `<LOCAL_GROUPS/>` you are right, not make sense in android

I'm checking information about `<LOCAL_USERS/>`
