### ISSUE TITLE
Version Client String

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#73]
A FI’s version client string (VERSIONCLIENT) helps identify which Agent is being used, what version, and on which operating system.

`Inventory Agent/0.2.0 (Linux; Android 4.0.4; Flyve MDM)`

/cc @g-bougard

**Comment by rafaelje** [comment]
@ajsb85 We can't create this name in the library we are going to add to the agent, this library just gets the name of the agent to add on field required

**Comment by ajsb85** [comment]
@rafaelje Yes, it's an argument (input) for the library.
This issue will be used as documentation, and you can create a reference from the PR.

**Comment by rafaelje** [comment]
Ok @ajsb85 fine
