### ISSUE TITLE
Fix BIOS keys

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-library#76]
Hi, @rafaelje 

Hector is using camelCase for the keys in the JSON file format for the BIOS.

Android report

```JSON
"bios": [
  {
    "bdate": "06\/07\/17",
    "bmanufacturer": "LGE",
    "mmanufacturer": "LGE",
    "smodel": "LG-K220",
    "ssn": "LGK220AISOLZ55"
  }
],
```

iPhone report
```JSON
"bios" : [
  {
    "motherboardModel" : "iPhone10,4",
    "biosManufacturer" : "Apple Inc.",
    "systemModel" : "D201AP"
  }
],
```

**Comment by rafaelje** [comment]
This is the last version of the inventory library 0.5.0:
```
	"bios": [{
		"biosReleaseDate": "01/04/17",
		"biosManufacturer": "LENOVO",
		"motherBoardManufacturer": "LENOVO",
		"motherBoardModel": "Lenovo A2010-l",
		"motherBoardSerialNumber": "0123456789ABCDEF"
	}]
```

This is the difference:
Android: motherBoardModel ....
iOS: motherboardModel ...

Keep the camelCase iOS?

**Comment by ajsb85** [comment]
Yes. Use the proposal of Hector.
And create the list for any language.
Here is the task:
https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/103

**Comment by ajsb85** [comment]
oh sorry, this proposal is OK

```JSON
"bios": [{
    "biosReleaseDate": "01/04/17",
    "biosManufacturer": "LENOVO",
    "motherBoardManufacturer": "LENOVO",
    "motherBoardModel": "Lenovo A2010-l",
    "motherBoardSerialNumber": "0123456789ABCDEF"
}]
```

So, the iOS Inventory Library need to fix it.

Thank you.
